# coding: utf-8

"""
    The Model API

    API to access the Virtual Satellite data model  # noqa: E501

    OpenAPI spec version: v0.0.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from plugins.VirtualSatelliteRestPlugin.generated_api.v0_0_1.swagger_client.api_client import ApiClient


class CAsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_ca(self, ca_uuid, full_qualified_name, repo_name, **kwargs):  # noqa: E501
        """Create CA  # noqa: E501

        This service creates a new CategoryAssignment and returns it  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_ca(ca_uuid, full_qualified_name, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ca_uuid: parent uuid (required)
        :param str full_qualified_name: Full qualified name of the CA type (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_ca_with_http_info(ca_uuid, full_qualified_name, repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.create_ca_with_http_info(ca_uuid, full_qualified_name, repo_name, **kwargs)  # noqa: E501
            return data

    def create_ca_with_http_info(self, ca_uuid, full_qualified_name, repo_name, **kwargs):  # noqa: E501
        """Create CA  # noqa: E501

        This service creates a new CategoryAssignment and returns it  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_ca_with_http_info(ca_uuid, full_qualified_name, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ca_uuid: parent uuid (required)
        :param str full_qualified_name: Full qualified name of the CA type (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ca_uuid', 'full_qualified_name', 'repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_ca" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ca_uuid' is set
        if self.api_client.client_side_validation and ('ca_uuid' not in params or
                                                       params['ca_uuid'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ca_uuid` when calling `create_ca`")  # noqa: E501
        # verify the required parameter 'full_qualified_name' is set
        if self.api_client.client_side_validation and ('full_qualified_name' not in params or
                                                       params['full_qualified_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `full_qualified_name` when calling `create_ca`")  # noqa: E501
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `create_ca`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ca_uuid' in params:
            path_params['caUuid'] = params['ca_uuid']  # noqa: E501
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'full_qualified_name' in params:
            query_params.append(('fullQualifiedName', params['full_qualified_name']))  # noqa: E501
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/ca/{caUuid}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_ca(self, ca_uuid, repo_name, **kwargs):  # noqa: E501
        """Delete CA  # noqa: E501

        This service deletes a CategoryAssignment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_ca(ca_uuid, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ca_uuid: Uuid of the CA (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_ca_with_http_info(ca_uuid, repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_ca_with_http_info(ca_uuid, repo_name, **kwargs)  # noqa: E501
            return data

    def delete_ca_with_http_info(self, ca_uuid, repo_name, **kwargs):  # noqa: E501
        """Delete CA  # noqa: E501

        This service deletes a CategoryAssignment.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_ca_with_http_info(ca_uuid, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ca_uuid: Uuid of the CA (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ca_uuid', 'repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_ca" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ca_uuid' is set
        if self.api_client.client_side_validation and ('ca_uuid' not in params or
                                                       params['ca_uuid'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ca_uuid` when calling `delete_ca`")  # noqa: E501
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `delete_ca`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ca_uuid' in params:
            path_params['caUuid'] = params['ca_uuid']  # noqa: E501
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/ca/{caUuid}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_ca(self, ca_uuid, repo_name, **kwargs):  # noqa: E501
        """Fetch CA  # noqa: E501

        This service fetches a CategoryAssignment  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_ca(ca_uuid, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ca_uuid: Uuid of the CA (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: ABeanCategoryAssignment
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_ca_with_http_info(ca_uuid, repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_ca_with_http_info(ca_uuid, repo_name, **kwargs)  # noqa: E501
            return data

    def get_ca_with_http_info(self, ca_uuid, repo_name, **kwargs):  # noqa: E501
        """Fetch CA  # noqa: E501

        This service fetches a CategoryAssignment  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_ca_with_http_info(ca_uuid, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ca_uuid: Uuid of the CA (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: ABeanCategoryAssignment
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ca_uuid', 'repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_ca" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ca_uuid' is set
        if self.api_client.client_side_validation and ('ca_uuid' not in params or
                                                       params['ca_uuid'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ca_uuid` when calling `get_ca`")  # noqa: E501
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `get_ca`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ca_uuid' in params:
            path_params['caUuid'] = params['ca_uuid']  # noqa: E501
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/ca/{caUuid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ABeanCategoryAssignment',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_ca(self, body, repo_name, **kwargs):  # noqa: E501
        """Put CA  # noqa: E501

        This service updates an existing CategoryAssignment  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_ca(body, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ABeanCategoryAssignment body: CA to put (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_ca_with_http_info(body, repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.put_ca_with_http_info(body, repo_name, **kwargs)  # noqa: E501
            return data

    def put_ca_with_http_info(self, body, repo_name, **kwargs):  # noqa: E501
        """Put CA  # noqa: E501

        This service updates an existing CategoryAssignment  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_ca_with_http_info(body, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ABeanCategoryAssignment body: CA to put (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_ca" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `put_ca`")  # noqa: E501
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `put_ca`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/ca', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
