# coding: utf-8

"""
    The Model API

    API to access the Virtual Satellite data model  # noqa: E501

    OpenAPI spec version: v0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from plugins.VirtualSatelliteRestPlugin.generated_api.v0_0_1.swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_root_sei(self, full_qualified_name, repo_name, **kwargs):  # noqa: E501
        """Create root SEI  # noqa: E501

        This service creates a new root StructuralElementInstance and returns its uuid  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_root_sei(full_qualified_name, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str full_qualified_name: Full qualified name of the SEI type (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_root_sei_with_http_info(full_qualified_name, repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.create_root_sei_with_http_info(full_qualified_name, repo_name, **kwargs)  # noqa: E501
            return data

    def create_root_sei_with_http_info(self, full_qualified_name, repo_name, **kwargs):  # noqa: E501
        """Create root SEI  # noqa: E501

        This service creates a new root StructuralElementInstance and returns its uuid  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_root_sei_with_http_info(full_qualified_name, repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str full_qualified_name: Full qualified name of the SEI type (required)
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['full_qualified_name', 'repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_root_sei" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'full_qualified_name' is set
        if self.api_client.client_side_validation and ('full_qualified_name' not in params or
                                                       params['full_qualified_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `full_qualified_name` when calling `create_root_sei`")  # noqa: E501
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `create_root_sei`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'full_qualified_name' in params:
            query_params.append(('fullQualifiedName', params['full_qualified_name']))  # noqa: E501
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/seis', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def force_synchronize(self, repo_name, **kwargs):  # noqa: E501
        """Trigger synchronization with the backend  # noqa: E501

        This service forces a synchronization with the backend.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.force_synchronize(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.force_synchronize_with_http_info(repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.force_synchronize_with_http_info(repo_name, **kwargs)  # noqa: E501
            return data

    def force_synchronize_with_http_info(self, repo_name, **kwargs):  # noqa: E501
        """Trigger synchronization with the backend  # noqa: E501

        This service forces a synchronization with the backend.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.force_synchronize_with_http_info(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method force_synchronize" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `force_synchronize`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/forceSync', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_concepts(self, repo_name, **kwargs):  # noqa: E501
        """Fetch a list of active Concepts  # noqa: E501

        This service fetches the active Concepts  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_concepts(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool only_active_concepts:
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: list[Concept]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_concepts_with_http_info(repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_concepts_with_http_info(repo_name, **kwargs)  # noqa: E501
            return data

    def get_concepts_with_http_info(self, repo_name, **kwargs):  # noqa: E501
        """Fetch a list of active Concepts  # noqa: E501

        This service fetches the active Concepts  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_concepts_with_http_info(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool only_active_concepts:
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: list[Concept]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repo_name', 'only_active_concepts', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_concepts" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `get_concepts`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'only_active_concepts' in params:
            query_params.append(('onlyActiveConcepts', params['only_active_concepts']))  # noqa: E501
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/concepts', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Concept]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_disciplines(self, repo_name, **kwargs):  # noqa: E501
        """Fetch a list of all Disciplines  # noqa: E501

        This service fetches the existing Disciplines  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_disciplines(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: list[BeanDiscipline]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_disciplines_with_http_info(repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_disciplines_with_http_info(repo_name, **kwargs)  # noqa: E501
            return data

    def get_disciplines_with_http_info(self, repo_name, **kwargs):  # noqa: E501
        """Fetch a list of all Disciplines  # noqa: E501

        This service fetches the existing Disciplines  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_disciplines_with_http_info(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: list[BeanDiscipline]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_disciplines" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `get_disciplines`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/disciplines', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[BeanDiscipline]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_repositpry_discipline(self, repo_name, **kwargs):  # noqa: E501
        """Fetch discipline of the repository  # noqa: E501

        This service fetches the discipline of the repository  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_repositpry_discipline(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: BeanDiscipline
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_repositpry_discipline_with_http_info(repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_repositpry_discipline_with_http_info(repo_name, **kwargs)  # noqa: E501
            return data

    def get_repositpry_discipline_with_http_info(self, repo_name, **kwargs):  # noqa: E501
        """Fetch discipline of the repository  # noqa: E501

        This service fetches the discipline of the repository  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_repositpry_discipline_with_http_info(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: BeanDiscipline
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_repositpry_discipline" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `get_repositpry_discipline`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/modelRepository', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BeanDiscipline',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_rolemanagement_discipline(self, repo_name, **kwargs):  # noqa: E501
        """Fetch discipline of the rolemanagement  # noqa: E501

        This service fetches the discipline of the rolemanagement  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_rolemanagement_discipline(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: BeanDiscipline
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_rolemanagement_discipline_with_http_info(repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_rolemanagement_discipline_with_http_info(repo_name, **kwargs)  # noqa: E501
            return data

    def get_rolemanagement_discipline_with_http_info(self, repo_name, **kwargs):  # noqa: E501
        """Fetch discipline of the rolemanagement  # noqa: E501

        This service fetches the discipline of the rolemanagement  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_rolemanagement_discipline_with_http_info(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: BeanDiscipline
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_rolemanagement_discipline" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `get_rolemanagement_discipline`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/rolemanagement', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BeanDiscipline',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_root_seis(self, repo_name, **kwargs):  # noqa: E501
        """Fetch a list of root SEIs  # noqa: E501

        This service fetches the root StructuralElementInstances. It can be used as an entry point into the data model.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_root_seis(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: list[ABeanStructuralElementInstance]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_root_seis_with_http_info(repo_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_root_seis_with_http_info(repo_name, **kwargs)  # noqa: E501
            return data

    def get_root_seis_with_http_info(self, repo_name, **kwargs):  # noqa: E501
        """Fetch a list of root SEIs  # noqa: E501

        This service fetches the root StructuralElementInstances. It can be used as an entry point into the data model.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_root_seis_with_http_info(repo_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repo_name: Name of the repository (required)
        :param bool sync: Synchronize with the repository on this request
        :param bool build: Build when synchronizing on this request
        :return: list[ABeanStructuralElementInstance]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repo_name', 'sync', 'build']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_root_seis" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repo_name' is set
        if self.api_client.client_side_validation and ('repo_name' not in params or
                                                       params['repo_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo_name` when calling `get_root_seis`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'repo_name' in params:
            path_params['repoName'] = params['repo_name']  # noqa: E501

        query_params = []
        if 'sync' in params:
            query_params.append(('sync', params['sync']))  # noqa: E501
        if 'build' in params:
            query_params.append(('build', params['build']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic']  # noqa: E501

        return self.api_client.call_api(
            '/repository/{repoName}/seis', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ABeanStructuralElementInstance]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
