# coding: utf-8

"""
    The Model API

    API to access the Virtual Satellite data model  # noqa: E501

    OpenAPI spec version: v0.0.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from plugins.VirtualSatelliteRestPlugin.generated_api.v0_0_1.swagger_client.configuration import Configuration


class ABeanUnitValueProperty(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unit_bean': 'ABeanUnitAUnit'
    }

    attribute_map = {
        'unit_bean': 'unitBean'
    }

    def __init__(self, unit_bean=None, _configuration=None):  # noqa: E501
        """ABeanUnitValueProperty - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._unit_bean = None
        self.discriminator = None

        if unit_bean is not None:
            self.unit_bean = unit_bean

    @property
    def unit_bean(self):
        """Gets the unit_bean of this ABeanUnitValueProperty.  # noqa: E501

        Unit of the bean  # noqa: E501

        :return: The unit_bean of this ABeanUnitValueProperty.  # noqa: E501
        :rtype: ABeanUnitAUnit
        """
        return self._unit_bean

    @unit_bean.setter
    def unit_bean(self, unit_bean):
        """Sets the unit_bean of this ABeanUnitValueProperty.

        Unit of the bean  # noqa: E501

        :param unit_bean: The unit_bean of this ABeanUnitValueProperty.  # noqa: E501
        :type: ABeanUnitAUnit
        """

        self._unit_bean = unit_bean

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ABeanUnitValueProperty, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ABeanUnitValueProperty):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ABeanUnitValueProperty):
            return True

        return self.to_dict() != other.to_dict()
