# coding: utf-8

"""
    The Model API

    API to access the Virtual Satellite data model  # noqa: E501

    OpenAPI spec version: v0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from plugins.VirtualSatelliteRestPlugin.generated_api.v0_0_1.swagger_client.configuration import Configuration


class ABeanProperty(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_calculated': 'bool',
        'property_type': 'str',
        'uuid': 'str'
    }

    attribute_map = {
        'is_calculated': 'isCalculated',
        'property_type': 'propertyType',
        'uuid': 'uuid'
    }

    discriminator_value_class_map = {
        'BeanPropertyString': 'BeanPropertyString',
        'BeanPropertyInt': 'BeanPropertyInt',
        'ABeanValueProperty': 'ABeanValueProperty',
        'BeanPropertyFloat': 'BeanPropertyFloat',
        'BeanPropertyEnum': 'BeanPropertyEnum',
        'BeanPropertyComposed': 'BeanPropertyComposed',
        'BeanPropertyResource': 'BeanPropertyResource',
        'ABeanUnitValueProperty': 'ABeanUnitValueProperty',
        'BeanPropertyReference': 'BeanPropertyReference',
        'BeanPropertyBoolean': 'BeanPropertyBoolean'
    }

    def __init__(self, is_calculated=None, property_type=None, uuid=None, _configuration=None):  # noqa: E501
        """ABeanProperty - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._is_calculated = None
        self._property_type = None
        self._uuid = None
        self.discriminator = 'propertyType'

        if is_calculated is not None:
            self.is_calculated = is_calculated
        if property_type is not None:
            self.property_type = property_type
        self.uuid = uuid

    @property
    def is_calculated(self):
        """Gets the is_calculated of this ABeanProperty.  # noqa: E501

        If true this property is calculated by an equation, thus it should not be changed via the API  # noqa: E501

        :return: The is_calculated of this ABeanProperty.  # noqa: E501
        :rtype: bool
        """
        return self._is_calculated

    @is_calculated.setter
    def is_calculated(self, is_calculated):
        """Sets the is_calculated of this ABeanProperty.

        If true this property is calculated by an equation, thus it should not be changed via the API  # noqa: E501

        :param is_calculated: The is_calculated of this ABeanProperty.  # noqa: E501
        :type: bool
        """

        self._is_calculated = is_calculated

    @property
    def property_type(self):
        """Gets the property_type of this ABeanProperty.  # noqa: E501

        Enum to idenify a property by it's type  # noqa: E501

        :return: The property_type of this ABeanProperty.  # noqa: E501
        :rtype: str
        """
        return self._property_type

    @property_type.setter
    def property_type(self, property_type):
        """Sets the property_type of this ABeanProperty.

        Enum to idenify a property by it's type  # noqa: E501

        :param property_type: The property_type of this ABeanProperty.  # noqa: E501
        :type: str
        """
        allowed_values = ["BOOLEAN", "STRING", "INT", "FLOAT", "ENUM", "RESOURCE", "REFERENCE", "EREFERENCE", "COMPOSED"]  # noqa: E501
        if (self._configuration.client_side_validation and
                property_type not in allowed_values):
            raise ValueError(
                "Invalid value for `property_type` ({0}), must be one of {1}"  # noqa: E501
                .format(property_type, allowed_values)
            )

        self._property_type = property_type

    @property
    def uuid(self):
        """Gets the uuid of this ABeanProperty.  # noqa: E501

        Unique identifier for a bean  # noqa: E501

        :return: The uuid of this ABeanProperty.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ABeanProperty.

        Unique identifier for a bean  # noqa: E501

        :param uuid: The uuid of this ABeanProperty.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ABeanProperty, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ABeanProperty):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ABeanProperty):
            return True

        return self.to_dict() != other.to_dict()
