# coding: utf-8

"""
    The Model API

    API to access the Virtual Satellite data model  # noqa: E501

    OpenAPI spec version: v0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from plugins.VirtualSatelliteRestPlugin.generated_api.v0_0_1.swagger_client.configuration import Configuration


class AUnit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'symbol': 'str',
        'quantity_kind': 'AQuantityKind',
        'definition_uri': 'str',
        'name': 'str',
        'uuid': 'VirSatUuid'
    }

    attribute_map = {
        'description': 'description',
        'symbol': 'symbol',
        'quantity_kind': 'quantityKind',
        'definition_uri': 'definitionURI',
        'name': 'name',
        'uuid': 'uuid'
    }

    def __init__(self, description=None, symbol=None, quantity_kind=None, definition_uri=None, name=None, uuid=None, _configuration=None):  # noqa: E501
        """AUnit - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._symbol = None
        self._quantity_kind = None
        self._definition_uri = None
        self._name = None
        self._uuid = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if symbol is not None:
            self.symbol = symbol
        if quantity_kind is not None:
            self.quantity_kind = quantity_kind
        if definition_uri is not None:
            self.definition_uri = definition_uri
        if name is not None:
            self.name = name
        if uuid is not None:
            self.uuid = uuid

    @property
    def description(self):
        """Gets the description of this AUnit.  # noqa: E501


        :return: The description of this AUnit.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AUnit.


        :param description: The description of this AUnit.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def symbol(self):
        """Gets the symbol of this AUnit.  # noqa: E501


        :return: The symbol of this AUnit.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this AUnit.


        :param symbol: The symbol of this AUnit.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def quantity_kind(self):
        """Gets the quantity_kind of this AUnit.  # noqa: E501


        :return: The quantity_kind of this AUnit.  # noqa: E501
        :rtype: AQuantityKind
        """
        return self._quantity_kind

    @quantity_kind.setter
    def quantity_kind(self, quantity_kind):
        """Sets the quantity_kind of this AUnit.


        :param quantity_kind: The quantity_kind of this AUnit.  # noqa: E501
        :type: AQuantityKind
        """

        self._quantity_kind = quantity_kind

    @property
    def definition_uri(self):
        """Gets the definition_uri of this AUnit.  # noqa: E501


        :return: The definition_uri of this AUnit.  # noqa: E501
        :rtype: str
        """
        return self._definition_uri

    @definition_uri.setter
    def definition_uri(self, definition_uri):
        """Sets the definition_uri of this AUnit.


        :param definition_uri: The definition_uri of this AUnit.  # noqa: E501
        :type: str
        """

        self._definition_uri = definition_uri

    @property
    def name(self):
        """Gets the name of this AUnit.  # noqa: E501


        :return: The name of this AUnit.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AUnit.


        :param name: The name of this AUnit.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def uuid(self):
        """Gets the uuid of this AUnit.  # noqa: E501


        :return: The uuid of this AUnit.  # noqa: E501
        :rtype: VirSatUuid
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this AUnit.


        :param uuid: The uuid of this AUnit.  # noqa: E501
        :type: VirSatUuid
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AUnit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AUnit):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AUnit):
            return True

        return self.to_dict() != other.to_dict()
